'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmItem

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''tbcItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbcItem As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tbpNewItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpNewItem As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''uplNewItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplNewItem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''uplChild2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplChild2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblErrAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrAddItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uplParent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplParent As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddItem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtAddStockCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddStockCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPartNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''uplChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplChild As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlAddItem2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddItem2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbtnGenerateStockCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnGenerateStockCode As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtAddDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAddStockType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAddStockType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAddSubType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAddSubType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAddUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAddUOM As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAddEquipmentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAddEquipmentNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAddLocation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddLocation1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddLocation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddLocation2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAddMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddMinLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeAddMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeAddMinLevel As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revAddMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAddMinLevel As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAddMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddMaxLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeAddMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeAddMaxLevel As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revAddMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAddMaxLevel As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAddReorderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddReorderLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeAddReorderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeAddReorderLevel As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revAddReorderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAddReorderLevel As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAddOpeningBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddOpeningBal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeAddOpeningBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeAddOpeningBal As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revAddOpeningBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAddOpeningBal As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAddOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddOpeningTotalValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeAddOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeAddOpeningTotalValue As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revAddOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAddOpeningTotalValue As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblAUC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAUC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddItem As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divMsgBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMsgBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMsgAddStockCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddStockCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddPartNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddStockType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddStockType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddSubType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddSubType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddUOM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddEquipmentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddEquipmentNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddLocation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddLocation1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddLocation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddLocation2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddMinLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddMaxLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddReorderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddReorderLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddOpeningBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddOpeningBalance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddOpeningTotalValue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddItemOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddItemOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upgNewItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upgNewItem As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''tbpLocateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpLocateItem As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''uplLocateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplLocateItem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblErrLocateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrLocateItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLocateStockCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocateStockCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLocateLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocateLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLocateDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocateDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlLocateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocateStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnLocateGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateGo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLocateClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSearchResults As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''gdvLocateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvLocateItem As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlItemInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlItemInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgItemDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgItemDetails As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblErrSaveItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrSaveItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEditStockCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditStockCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEditPartNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPartNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlEditStockType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditStockType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEditSubType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditSubType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEditUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditUOM As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEditEquipmentNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditEquipmentNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEditLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditLocation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditLocation2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditMinLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeEditMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeEditMinLevel As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revEditMinLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revEditMinLevel As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtEditMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditMaxLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeEditMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeEditMaxLevel As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revEditMaxLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revEditMaxLevel As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtEditReOrderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditReOrderLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeEditReOrderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeEditReOrderLevel As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revEditReorderLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revEditReorderLevel As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtEditOpeningBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditOpeningBal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeEditOpeningBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeEditOpeningBal As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revEditOpeningBal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revEditOpeningBal As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtEditOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditOpeningTotalValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ftbeEditOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ftbeEditOpeningTotalValue As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''revEditOpeningTotalValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revEditOpeningTotalValue As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblDisplayAUC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayAUC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hidTransactiondate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidTransactiondate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblDisplayStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnLocateEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateEdit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLocateDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateDel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLocateClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateClose As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLocateReopen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateReopen As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnLocateSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLocateCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upgLocateItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upgLocateItem As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''tbpPrintItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpPrintItem As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''uplPrintItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplPrintItem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblErrPrintItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrPrintItem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPrintOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrintOption As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSortBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSortBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rblStockCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblStockCode As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtStockCodeFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStockCodeFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''aceStockCodeFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aceStockCodeFrom As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txtStockCodeTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStockCodeTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''aceStockCodeTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aceStockCodeTo As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''chkStockType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStockType As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''ddlItemStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlItemStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReportClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReportClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rvr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvr As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''ObjectDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''gdvItemReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvItemReport As Global.System.Web.UI.WebControls.GridView
End Class
