'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmStore

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''tbcStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbcStore As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''tbpNewStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpNewStore As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''uplNewStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplNewStore As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlAddStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddStore As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblErrAddStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrAddStore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStoreCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStoreCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStoreName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStoreName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAddressType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAddressType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAddressBlockHouseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddressBlockHouseNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStreetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStreetName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFloorNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFloorNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBuildingName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuildingName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPostalCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPerson As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTelNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFaxNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFaxNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtOtherInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOtherInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStore As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divMsgBoxAddStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMsgBoxAddStore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMsgStoreCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgStoreCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgStoreName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgStoreName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddressType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddressType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgAddressNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAddressNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgStreetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgStreetName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgFloorNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgFloorNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgUnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgUnitNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgBuildingName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgBuildingName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgPostalCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgContactPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgTelephoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgTelephoneNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgFaxNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgFaxNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMsgOtherInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgOtherInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAddStoreOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStoreOK As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upgNewStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upgNewStore As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''tbpLocateStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpLocateStore As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''uplLocateStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplLocateStore As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblErrLocateStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrLocateStore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlLocateStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocateStore As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtLocateStoreName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocateStoreName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlLocateStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLocateStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnLocateGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateGo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLocateClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearchResults As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSearchResults As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''gdvLocateStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvLocateStore As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlStoreInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStoreInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblErrSaveStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrSaveStore As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEditStoreCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditStoreCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEditStoreName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditStoreName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlEditAddressType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEditAddressType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEditBlockHouseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditBlockHouseNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditStreetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditStreetName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditFloorNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditFloorNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditUnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditUnitNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditBuildingName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditBuildingName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditPostalCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditContactPerson As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditTelephoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditTelephoneNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditFaxNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditFaxNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEditOtherInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditOtherInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDisplayStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtnLocateEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateEdit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLocateDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateDel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLocateClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateClose As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnLocateReopen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnLocateReopen As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnLocateSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLocateCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLocateCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upgLocateStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upgLocateStore As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''tbpPrintStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbpPrintStore As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''uplPrintStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplPrintStore As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPDF As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rvr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rvr As Global.Microsoft.Reporting.WebForms.ReportViewer

    '''<summary>
    '''ObjectDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectDataSource1 As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
